#!/usr/local/cpanel/3rdparty/bin/perl
# cpanel - find-latest-version                  Copyright(c) 2022 cPanel, L.L.C.
#                                                           All rights Reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited
#
# This provides incremental updates to existing packages in EasyApache4.
package ea_container_memcached::find_latest_version;

use strict;
use warnings;

use lib "../ea-tools/lib/ea4_tool";    # assumes ea-tools is checked out next to this repo
use ea4_tool::util ();

sub get_version {
    my $version = ea4_tool::util::get_docker_hub_newest_release( name => "container-memcached", docker_name => "memcached", namespace => "library", minor => "6", increment => 2 );

    print "VERSION :$version:\n";

    return;
}

unless ( caller() ) {
    get_version ();
}

