#!/usr/local/cpanel/3rdparty/bin/perl
# cpanel - ea-podman-local-dir-setup                 Copyright 2022 cPanel, Inc.
#                                                           All rights Reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use strict;
use warnings;

package scripts::ea_podman_local_dir_setup;

use Path::Tiny 'path';

run(@ARGV) if !caller;

sub run {
    my ( $host_path, @ports ) = @_;

    die "Must not have ports ($host_path)\n" if @ports;

    return add($host_path);
}

################
#### commands ##
################

sub add {
    my ($host_path) = @_;

    _bail("$host_path appears to have setup already; aborting so we don’t break anything") if -d $host_path && !_memcached_dir_is_empty($host_path);

    return;
}

###############
#### helpers ##
###############

sub _bail {
    my ($msg) = @_;

    chomp($msg);
    warn "$msg\n";

    exit(1);    # there is no return()ing from this lol
}

sub _memcached_dir_is_empty {
    my ($dir) = @_;
    my @contents = path($dir)->children;
    return 1 if !@contents;
    return;
}

1;
